### ISSUE TITLE
grid view for doclist

### ISSUE THREAD

**Issue by PalmerAL** [PalmerAL/scratchpad#155]
previously mentioned in #2 

@nt1m I have a prototype of this at https://standaert.net/scratchpad/doclist/#grid. It picks an image from the document and uses that for the background, which I think is more readable and useful than a screenshot of the text (which I don't think is possible to generate anyway). What should the ui for switching between grid and list views look like, though?

**Comment by PalmerAL** [comment]
Also, I won't have time to work on this again until next weekend.

**Comment by nt1m** [comment]
@PalmerAL The UI itself is fine, but it doesn't match the spec [1]. I like the idea of using an image from the document, but I have a few suggestions : use a fallback UI when there is no image, use background-position: center on the image.
As for the switching UI, something like how google docs works should be fine.
1 : http://www.google.com/design/spec/components/grid-lists.html#grid-lists-specs

**Comment by PalmerAL** [comment]
Updated to match spec. Depends on nt1m/material-framework#172

What should the fallback be? Right now, there is just a light gray background, but it doesn't work well when most of the tiles don't have an image.

**Comment by nt1m** [comment]
Merged your PR. As for the fallback, I'll create an image for you.

**Comment by nt1m** [comment]
https://gist.github.com/anonymous/4ad520dd8362e6be0eba

**Comment by PalmerAL** [comment]
Done. Vexigner is amazing!

**Comment by nt1m** [comment]
@PalmerAL Thanks :)
Looks great ! Now that I see it live, here are some tweaks I would make : 
- Add a gray background on the tiles (#f1f1f1 ?) so that the tiles stand out from the page background
- Use a #333 background color on tile-image
- Use background-size: contain, so the image isn't positioned strangely
In the barack obama pic case, using bg-size: cover showed Obama's chest
background-size: contain should display all picture sizes in a acceptable way

Also, the placeholder didn't work for me.

Mockup :
![screen shot 2015-05-03 at 00 23 13](https://cloud.githubusercontent.com/assets/1795135/7442989/9b50c452-f12a-11e4-95a7-1261de94105a.png)
v2 of the placeholder : https://gist.github.com/anonymous/8d70bd9da7feec82b36c

**Comment by nt1m** [comment]
As for the alignment, 
- Align everything on the left on desktop and tablet displays
- Align to the center on phone displays

**Comment by PalmerAL** [comment]
<blockquote>
Also, the placeholder didn't work for me.
</blockquote>
This should work now. Somehow, cloudflare's cache didn't update like it should.

**Comment by PalmerAL** [comment]
PR: #156

**Comment by PalmerAL** [comment]
I'm not sure the background-size:contain is a good idea, as the tiles should all look fairly uniform. With a bunch of different sized images, the tiles start to look messy, especially when there is just a small gap between the background and the tile edge.

**Comment by nt1m** [comment]
I noticed you added the ripple effect, looks nice, however the circle ripple would fit better here, as the tile is (nearly) square.

**Comment by PalmerAL** [comment]
Done.

**Comment by nt1m** [comment]
As for the bg-size, cover is definitvely better than contain, but I'm concerned about the positioning, as it doesn't look right in some cases.

**Comment by PalmerAL** [comment]
#156
